name: Docker Pull Example
on: [push]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Pull Docker image
        run: docker pull kakaxi088/zubo:v3.2.0
      
      - name: Run Docker container
        run: |
          docker run \
            --name zubo-container \
            kakaxi088/zubo:v3.2.0
